set -g base-index 1

# Enable mouse & Copy/Paste - Requirements: xclip
set -g mouse on 
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection c"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Use vim keybindings to switch panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use vim keybindings to resize panes
# bind -n C-h resize-pane -L
# bind -n C-j resize-pane -D
# bind -n C-k resize-pane -U
# bind -n C-l resize-pane -R

# Change prefix
unbind-key C-b
set -g prefix 'C-\'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jonmosco/kube-tmux'

# Update interval
set -g status-interval 1
set -g status-justify left

# Status bar
# set -g status-style "bg=#262626,fg=#ffffff"
set -g status-right-length 220

# set -g status-right "#[fg=#3a3a3a,bg=#262626]#[fg=#ffffff,bg=#3a3a3a] ⎈ #(/bin/bash $HOME/.config/tmux/plugins/kube-tmux/kube.tmux 250 red cyan) #[fg=#262626,bg=#3a3a3a]#[fg=#ffffff,bg=#262626] 🔋 #(cat /sys/class/power_supply/BAT0/capacity)% #[fg=#121212,bg=#262626]#[fg=#ffffff,bg=#121212] %I:%M %p "
# set -g status-right "#[fg=#3a3a3a,bg=#262626]#[fg=#ffffff,bg=#3a3a3a] ⎈ #(/bin/bash $HOME/.config/tmux/plugins/kube-tmux/kube.tmux 250 red cyan) #[fg=#262626,bg=#3a3a3a]#[fg=#ffffff,bg=#262626, italics] 🎵 #(~/.config/tmux/scripts/spotify-scroll.sh) #[fg=#121212,bg=#262626, none]#[fg=#ffffff,bg=#121212] %I:%M %p "
set -g status-right "#[fg=#3a3a3a,bg=default]#[fg=#ffffff,bg=#3a3a3a] ⎈#(bash $HOME/.config/tmux/plugins/kube-tmux/kube.tmux 250 red cyan) #[fg=#262626,bg=#3a3a3a]#[fg=#ffffff,bg=#262626, italics] 🎵 #(~/.config/tmux/scripts/spotify-scroll.sh) #[fg=#121212,bg=#262626, none]#[fg=#ffffff,bg=#121212] %I:%M %p "

# tmux-resurrect
# set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

bind-key "o" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

run '~/.config/tmux/plugins/tpm/tpm'
